const blackCards = [
  { id: 'b1', text: 'My therapist says I need to stop ___.', pick: 1 },
  { id: 'b2', text: 'Scientists have discovered that ___ cures depression.', pick: 1 },
  { id: 'b3', text: 'The leading cause of divorce in America is ___.', pick: 1 },
  { id: 'b4', text: 'My safe word is ___.', pick: 1 },
  { id: 'b5', text: "I've been sober for three months. I owe it all to ___.", pick: 1 },
  { id: 'b6', text: 'Next from the creators of Squid Game: ___.', pick: 1 },
  { id: 'b7', text: 'Doctors HATE this one weird trick: ___.', pick: 1 },
  { id: 'b8', text: 'I want to die doing what I love: ___.', pick: 1 },
  { id: 'b9', text: 'Step one: ___. Step two: ___. Step three: profit.', pick: 2 },
  { id: 'b10', text: "What's my secret hobby?", pick: 1 },
  { id: 'b11', text: "In my will, I'm leaving everything to ___.", pick: 1 },
  { id: 'b12', text: "My dating profile says I'm passionate about ___ and ___.", pick: 2 },
  { id: 'b13', text: "Netflix's newest documentary: ___.", pick: 1 },
  { id: 'b14', text: 'What did Grandma leave in the attic?', pick: 1 },
  { id: 'b15', text: 'The FDA just approved ___ as a dietary supplement.', pick: 1 },
  { id: 'b16', text: "I don't see color. I see ___.", pick: 1 },
  { id: 'b17', text: 'During the apocalypse, the only survivors will be ___ and ___.', pick: 2 },
  { id: 'b18', text: "What's the new relationship status Facebook should add?", pick: 1 },
  { id: 'b19', text: 'Before dying, my father whispered one last secret: ___.', pick: 1 },
  { id: 'b20', text: 'The next iPhone will come with built-in ___.', pick: 1 },
  { id: 'b21', text: "What am I bringing to Thanksgiving dinner?", pick: 1 },
  { id: 'b22', text: 'My New Year\'s resolution is to finally get in shape using ___.', pick: 1 },
  { id: 'b23', text: "The museum's most controversial exhibit: ___.", pick: 1 },
  { id: 'b24', text: 'The government has been putting ___ in the water supply.', pick: 1 },
  { id: 'b25', text: 'I got fired again, this time for ___.', pick: 1 },
  { id: 'b26', text: '___ is the new black.', pick: 1 },
  { id: 'b27', text: "For my next TED talk, I'll be speaking about ___.", pick: 1 },
  { id: 'b28', text: "Why can't I sleep at night? ___.", pick: 1 },
  { id: 'b29', text: 'The secret to a happy marriage is ___.', pick: 1 },
  { id: 'b30', text: 'What ruined my childhood?', pick: 1 },
  { id: 'b31', text: 'What\'s the most patriotic thing an American can do?', pick: 1 },
  { id: 'b32', text: "What's the new Olympic sport?", pick: 1 },
  { id: 'b33', text: "What's in the box?!", pick: 1 },
  { id: 'b34', text: "What am I doing wrong in the bedroom?", pick: 1 },
  { id: 'b35', text: "I told my kids that babies come from ___.", pick: 1 },
  { id: 'b36', text: "Kids these days are all about ___ and ___.", pick: 2 },
  { id: 'b37', text: 'The new wellness trend: microdosing ___.', pick: 1 },
  { id: 'b38', text: 'What should never be mixed with alcohol?', pick: 1 },
  { id: 'b39', text: '___ is just ___ for adults.', pick: 2 },
  { id: 'b40', text: "What's the most dangerous thing in my medicine cabinet?", pick: 1 },
  { id: 'b41', text: "During the job interview, I said my greatest weakness is ___.", pick: 1 },
  { id: 'b42', text: 'The number one cause of global warming is ___.', pick: 1 },
  { id: 'b43', text: 'In my Tinder bio I describe myself as a ___.', pick: 1 },
  { id: 'b44', text: "What am I hiding under my mattress?", pick: 1 },
  { id: 'b45', text: "What do I do when no one's watching?", pick: 1 },
  { id: 'b46', text: 'The real reason Santa only comes once a year is ___.', pick: 1 },
  { id: 'b47', text: "What's the best way to ruin a first date?", pick: 1 },
  { id: 'b48', text: "My favorite hobby is ___, but only when I'm drunk.", pick: 1 },
  { id: 'b49', text: "What got me banned from the local library?", pick: 1 },
  { id: 'b50', text: 'Scientists have confirmed: too much ___ will kill you.', pick: 1 },
];

const whiteCards = [
  { id: 'w1', text: 'Accidental eye contact while eating a banana' },
  { id: 'w2', text: 'An unsolicited opinion from someone worse off than you' },
  { id: 'w3', text: "The lingering scent of someone else's bad decisions" },
  { id: 'w4', text: 'Emotional support alcohol' },
  { id: 'w5', text: 'Daddy issues with excellent credit' },
  { id: 'w6', text: 'Getting personally victimized by an automatic flush toilet' },
  { id: 'w7', text: 'A moist handshake and nowhere to wipe it' },
  { id: 'w8', text: 'Falling asleep during sex and pretending it was a power move' },
  { id: 'w9', text: 'Stress-crying in a Target' },
  { id: 'w10', text: 'Dying alone but with high-speed WiFi' },
  { id: 'w11', text: 'The raw power of a middle-aged man in cargo shorts' },
  { id: 'w12', text: 'Telling your therapist everything except the real problem' },
  { id: 'w13', text: "Sending 'new phone who dis' to your estranged father" },
  { id: 'w14', text: 'Passive-aggressive sticky notes' },
  { id: 'w15', text: 'Blaming everything on Mercury retrograde' },
  { id: 'w16', text: 'An existential crisis during yoga' },
  { id: 'w17', text: 'Getting catfished by someone worse than your ex' },
  { id: 'w18', text: "Weaponizing a baby's cuteness for financial gain" },
  { id: 'w19', text: 'Achieving nothing but maintaining high self-esteem' },
  { id: 'w20', text: 'Drunk texting your ex, your priest, and your boss in sequence' },
  { id: 'w21', text: 'A horny ghost who just wants to be held' },
  { id: 'w22', text: 'The audacity to ask for a receipt at a food truck' },
  { id: 'w23', text: 'Being the worst version of yourself, confidently' },
  { id: 'w24', text: "A passive-aggressive 'per my last email'" },
  { id: 'w25', text: 'The suspicious van parked outside all week' },
  { id: 'w26', text: 'Hiding in the bathroom at your own party' },
  { id: 'w27', text: 'A LinkedIn post about a humiliating personal failure' },
  { id: 'w28', text: 'Reading self-help books without changing anything' },
  { id: 'w29', text: 'The confidence of a man who has never been wrong' },
  { id: 'w30', text: "Your body's last text before it gives up" },
  { id: 'w31', text: 'Microwaving fish in the office kitchen' },
  { id: 'w32', text: 'Getting too real on a first date' },
  { id: 'w33', text: 'A strong unwanted hug from an aunt' },
  { id: 'w34', text: "Blacking out at a child's birthday party" },
  { id: 'w35', text: 'The smell of a Walmart at 2am' },
  { id: 'w36', text: 'Complaining about your great life on social media' },
  { id: 'w37', text: 'A surprise pregnancy announcement at a divorce party' },
  { id: 'w38', text: 'Getting caught watching Netflix during a Zoom call' },
  { id: 'w39', text: 'A deeply personal confession at an inappropriate time' },
  { id: 'w40', text: 'Oversharing your medical history to a barista' },
  { id: 'w41', text: 'The forbidden love between a man and his inflatable pool toy' },
  { id: 'w42', text: "Forgetting the word for 'fork' and having a full breakdown" },
  { id: 'w43', text: "Accidentally calling your boss 'sexy'" },
  { id: 'w44', text: 'A 40-year-old playing video games with surgical intensity' },
  { id: 'w45', text: "Finding your parents' 'special drawer'" },
  { id: 'w46', text: 'The courage that comes after three drinks' },
  { id: 'w47', text: 'Furiously doing something incredibly inappropriate' },
  { id: 'w48', text: 'A sex tape with surprisingly poor production value' },
  { id: 'w49', text: 'The gentle disappointment of a parent who has given up' },
  { id: 'w50', text: 'Emotional dumping on a first date' },
  { id: 'w51', text: "Crying in a Wendy's drive-through" },
  { id: 'w52', text: 'An intervention that becomes a roast' },
  { id: 'w53', text: 'Too many feelings in a public restroom' },
  { id: 'w54', text: 'Haunted genitals' },
  { id: 'w55', text: 'An impressive mustache and nothing else' },
  { id: 'w56', text: "The look on your parents' faces when they find your browser history" },
  { id: 'w57', text: "Enthusiastically doing something you clearly don't understand" },
  { id: 'w58', text: 'A very professional breakdown' },
  { id: 'w59', text: 'A Yelp review about your ex' },
  { id: 'w60', text: 'Buying 47 things on Amazon at 3am' },
  { id: 'w61', text: "Responding to 'what's wrong?' with 'nothing'" },
  { id: 'w62', text: "Texting your mom asking what she meant by 'K'" },
  { id: 'w63', text: 'Watching true crime instead of fixing your own life' },
  { id: 'w64', text: 'A very messy situationship' },
  { id: 'w65', text: 'Gaslighting yourself in the mirror' },
  { id: 'w66', text: "A motivational poster that just says 'no'" },
  { id: 'w67', text: "A dog's unexpected betrayal" },
  { id: 'w68', text: "Cocaine at a kid's birthday party" },
  { id: 'w69', text: 'Aggressive, sustained eye contact with a stranger' },
  { id: 'w70', text: 'Sending a voice memo by mistake and immediately dying inside' },
  { id: 'w71', text: 'Finding $20 in an old coat and spending it on nonsense' },
  { id: 'w72', text: 'Crying-laughing at a funeral' },
  { id: 'w73', text: "An intrusive thought that won't leave" },
  { id: 'w74', text: 'Spontaneous human combustion' },
  { id: 'w75', text: 'Getting rejected by your own reflection' },
  { id: 'w76', text: 'Waking up next to someone and immediately forgetting their name' },
  { id: 'w77', text: 'A surprisingly aggressive Elf on the Shelf' },
  { id: 'w78', text: "The confidence of someone who's never paid rent" },
  { id: 'w79', text: 'Accidentally joining a cult during a rough week' },
  { id: 'w80', text: 'Being too broke to have an addiction' },
  { id: 'w81', text: 'The horrors of a shared Google Calendar' },
  { id: 'w82', text: 'A soft launch of a mental breakdown' },
  { id: 'w83', text: 'Weaponized vulnerability' },
  { id: 'w84', text: "Ending a serious conversation with 'lol jk'" },
  { id: 'w85', text: "Getting a tattoo of your ex's face as a warning to others" },
  { id: 'w86', text: 'A vibrator on silent mode in the airport security line' },
  { id: 'w87', text: 'Forgetting your safeword' },
  { id: 'w88', text: 'Telling someone they have a great personality' },
  { id: 'w89', text: 'Pooping in Starbucks for the free WiFi' },
  { id: 'w90', text: 'A Tinder match who looks exactly like your estranged parent' },
  { id: 'w91', text: 'Having an emotion about a mattress commercial' },
  { id: 'w92', text: "An apology that's just more explaining" },
  { id: 'w93', text: 'A man who has never apologized in his life' },
  { id: 'w94', text: 'Enthusiastically misreading the room' },
  { id: 'w95', text: 'A full mental breakdown with excellent snacks' },
  { id: 'w96', text: 'Choosing violence' },
  { id: 'w97', text: 'Stress-eating an entire cheese board alone' },
  { id: 'w98', text: 'The forbidden attraction to someone deeply inappropriate' },
  { id: 'w99', text: "A LinkedIn connection request from your dealer" },
  { id: 'w100', text: 'The dangerous thrill of Reply All' },
  { id: 'w101', text: "Asking 'does this look infected?' in mixed company" },
  { id: 'w102', text: 'The aftermath of trusting a fart' },
  { id: 'w103', text: 'An NFT of your own tears' },
  { id: 'w104', text: 'Sending a flirty text to your group chat by mistake' },
  { id: 'w105', text: 'A passive-aggressive fruit basket' },
  { id: 'w106', text: 'Narrating your own life in third person during a crisis' },
  { id: 'w107', text: "Consulting a therapist who is clearly more messed up than you" },
  { id: 'w108', text: 'The 3am version of yourself making permanent decisions' },
  { id: 'w109', text: 'A very public divorce in a very small town' },
  { id: 'w110', text: 'Getting a restraining order from your own subconscious' },
  { id: 'w111', text: 'The unbearable weight of having options' },
  { id: 'w112', text: 'Accidentally subscribing to your own problems' },
  { id: 'w113', text: 'Showing up to therapy and just screaming for 50 minutes' },
  { id: 'w114', text: 'A surprisingly erotic tax return' },
  { id: 'w115', text: 'Telling your coworker they remind you of your mom' },
  { id: 'w116', text: 'Falling into a well and updating your status about it' },
  { id: 'w117', text: 'Saying "I love you" by accident to a customer service rep' },
  { id: 'w118', text: 'An intimate relationship with a vending machine' },
  { id: 'w119', text: 'The hot mess who somehow got promoted' },
  { id: 'w120', text: 'Accidentally sending your nudes to a school email list' },
  { id: 'w121', text: 'Screaming into the void until the void screams back' },
  { id: 'w122', text: 'A fully grown adult eating cereal for dinner and crying' },
  { id: 'w123', text: 'Looking directly at your problems and choosing Netflix' },
  { id: 'w124', text: 'A very questionable life coach who lives in a van' },
  { id: 'w125', text: 'Crying at a Pixar movie for an unreasonable amount of time' },
  { id: 'w126', text: 'A very polite intervention nobody wanted' },
  { id: 'w127', text: 'Convincing yourself that red wine counts as self-care' },
  { id: 'w128', text: 'An overly personal handshake at a job interview' },
  { id: 'w129', text: 'The smell of spiritual defeat' },
  { id: 'w130', text: 'Passive income and active depression' },
  { id: 'w131', text: 'Desperately explaining a meme to someone who has already moved on' },
  { id: 'w132', text: "Rage-refreshing your ex's social media at 4am" },
  { id: 'w133', text: 'A motivational speech from someone clearly unqualified' },
  { id: 'w134', text: 'The panic of being on hold for 45 minutes about nothing' },
  { id: 'w135', text: "That one drawer in the kitchen that's pure chaos" },
  { id: 'w136', text: 'A restraining order sent with heart emojis' },
  { id: 'w137', text: "Saying 'it is what it is' while clearly it is not" },
  { id: 'w138', text: 'Your Spotify Wrapped arriving with devastating accuracy' },
  { id: 'w139', text: 'Getting personally offended by a salad' },
  { id: 'w140', text: "Answering 'I'm fine' in a voice that says everything" },
  { id: 'w141', text: 'A very formal email written while absolutely hammered' },
  { id: 'w142', text: 'Having a full character arc in the self-checkout line' },
  { id: 'w143', text: 'A deeply upsetting dream that technically counts as self-care' },
  { id: 'w144', text: 'Overcorrecting after a mistake until everything is worse' },
  { id: 'w145', text: "A coping mechanism that's really more of an addiction" },
  { id: 'w146', text: 'Making an enemies list and running out of room' },
  { id: 'w147', text: 'The decision to finally do something, followed immediately by a nap' },
  { id: 'w148', text: 'Proposing during someone else\'s wedding toast' },
  { id: 'w149', text: 'A surprise party thrown for the wrong person' },
  { id: 'w150', text: 'Crying because you\'re full but there\'s still food' },
  { id: 'w151', text: 'Explaining your kink to your insurance company' },
  { id: 'w152', text: "A very enthusiastic stranger's completely wrong life advice" },
  { id: 'w153', text: 'The mildly erotic sensation of someone else paying the bill' },
  { id: 'w154', text: 'Reheated grief from a previous relationship' },
  { id: 'w155', text: 'Starting a fight at a funeral and winning' },
  { id: 'w156', text: "The healing power of other people's problems" },
  { id: 'w157', text: 'A deeply regrettable karaoke performance' },
  { id: 'w158', text: 'Forgetting where you parked but finding clarity about your life' },
  { id: 'w159', text: 'Falling asleep on public transit and waking up crying' },
  { id: 'w160', text: 'Mistaking passion for acid reflux' },
  { id: 'w161', text: 'Updating your will as a passive-aggressive act of revenge' },
  { id: 'w162', text: 'Screaming internally while smiling at a coworker' },
  { id: 'w163', text: 'Accidentally becoming the main character' },
  { id: 'w164', text: 'An emotional support snack that just is not enough' },
  { id: 'w165', text: 'An unreasonably detailed answer to "how are you?"' },
  { id: 'w166', text: 'Trying to rizz someone up at a Costco' },
  { id: 'w167', text: 'Absolutely destroying a buffet in front of people you want to impress' },
  { id: 'w168', text: 'Turning your trauma into a small business' },
  { id: 'w169', text: 'A surprisingly intimate moment with a stranger\'s dog' },
  { id: 'w170', text: 'The hot confidence of someone who has nothing to lose' },
  { id: 'w171', text: 'A suspiciously detailed Google search history' },
  { id: 'w172', text: "Calling in sick with 'a vibe issue'" },
  { id: 'w173', text: 'A single tear rolling down your face while eating fast food' },
  { id: 'w174', text: 'Misquoting scripture in your own favor' },
  { id: 'w175', text: 'A deeply personal PowerPoint presentation nobody wanted' },
  { id: 'w176', text: 'The sound of a romantic evening being ruined' },
  { id: 'w177', text: 'Your body finally releasing what you have been holding onto' },
  { id: 'w178', text: 'The chaos that follows one small unchecked notification' },
  { id: 'w179', text: 'Developing feelings for someone at a profoundly inappropriate time' },
  { id: 'w180', text: 'A passive income stream and crippling self-doubt' },
  { id: 'w181', text: 'Being absolutely certain about something completely wrong' },
  { id: 'w182', text: 'Chronic over-explaining to people who stopped listening' },
  { id: 'w183', text: 'A participation trophy for trying to have sex' },
  { id: 'w184', text: 'An unsolicited TED talk about a very niche interest' },
  { id: 'w185', text: 'The aggressive nostalgia of someone who peaked in high school' },
  { id: 'w186', text: 'Crying about something that happened in a movie 14 years ago' },
  { id: 'w187', text: 'A deeply misleading Airbnb listing' },
  { id: 'w188', text: 'A hotel minibar relationship that got completely out of hand' },
  { id: 'w189', text: "Giving unsolicited life advice from the bottom of a bottle" },
  { id: 'w190', text: "An unwanted erection at a very formal event" },
  { id: 'w191', text: 'Getting rickrolled by the universe' },
  { id: 'w192', text: 'A very public meltdown at a self-checkout machine' },
  { id: 'w193', text: 'The unbearable intimacy of sharing a hotel bathroom' },
  { id: 'w194', text: 'Aggressively normal behavior' },
  { id: 'w195', text: "Ghost-writing your own excuses" },
  { id: 'w196', text: 'The audacity' },
  { id: 'w197', text: 'A firmly passive-aggressive smile' },
  { id: 'w198', text: 'Absolutely nothing working out but remaining extremely confident' },
  { id: 'w199', text: 'Getting personally betrayed by a vending machine' },
  { id: 'w200', text: 'The decision to text your ex at 2am framed as personal growth' },
];

module.exports = { blackCards, whiteCards };
